TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io/graphql
PDL_SCOPE: dev-fss.pdl.pdl-api
SKJERMEDE_BASE_URL: https://skjermede-personer-pip.dev.intern.nav.no

NORG2_API_V1_URL: https://norg2.dev-fss-pub.nais.io/norg2/api/v1
PROXY_APP_CLIENT_ID: c6050231-3b9f-4173-8d1e-39b7e6e3392e

EREG_URL: https://ereg-services-q1.dev-fss-pub.nais.io/ereg/api

VEDTAK_FATTET_TOPIC: klage.vedtak-fattet.v1
DVH_STATISTIKK_TOPIC: klage.kabal-statistikk.v1
BEHANDLING_ENDRET_TOPIC_V2: klage.behandling-endret.v2
BEHANDLING_EVENTS_TOPIC: klage.behandling-events.v1

AIVEN_ES_HOST: elastic-klage-oppgave-es-nav-dev.aivencloud.com
AIVEN_ES_PORT: 26482
AIVEN_ES_SCHEME: https
AIVEN_ES_USE_SSL: true

SAF_BASE_URL: https://saf.dev-fss-pub.nais.io/
SAF_SCOPE: dev-fss.teamdokumenthandtering.saf-q1

KABAL_SAKSBEHANDLING: 07add1e7-7195-4c37-828d-fdf23ec6bef1
KABAL_FAGTEKSTREDIGERING: 94d34f17-e325-4ed6-9667-d23041a3f40c
KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

KABAL_ADMIN: a9f5ef81-4e81-42e8-b368-0273071b64b9

CLAM_AV_URL: http://clamav.clamav/scan

FERDIGSTILLE_DOKUMENTER_DELAY_MILLIS: 20000