SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
SLACK_URL: localhost:8080
SLACK_CHANNEL_ID: #none
NAIS_CLUSTER_NAME: local
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
NORG2_API_V1_URL: local
NORG2_APIKEY: 123
OPPGAVE_APIKEY: 456
STS_APIKEY: 789
PDL_BASE_URL: local
PDL_APIKEY: 159
SAF_BASE_URL: local
SAF_SCOPE: local

nais:
  cluster:
    name: local
AIVEN_ES_SCHEME: http
AIVEN_ES_HOST: localhost
AIVEN_ES_PORT: 9200
AIVEN_ES_USE_SSL: false
ELASTIC_USERNAME: elasticsearch
ELASTIC_PASSWORD: password

NAIS_DATABASE_KABAL_API_KABAL_API_USERNAME: klage
NAIS_DATABASE_KABAL_API_KABAL_API_PASSWORD: klage
NAIS_DATABASE_KABAL_API_KABAL_API_DATABASE: kabal-api
NAIS_DATABASE_KABAL_API_KABAL_API_HOST: localhost
NAIS_DATABASE_KABAL_API_KABAL_API_PORT: 5432

KABAL_OPPGAVESTYRING_ALLE_ENHETER: xxxx
KABAL_MALTEKSTREDIGERING: xxxx
KABAL_SAKSBEHANDLING: 07add1e7-7195-4c37-828d-fdf23ec6bef1
KABAL_FAGTEKSTREDIGERING: 94d34f17-e325-4ed6-9667-d23041a3f40c
KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: ea930b6b-9397-44d9-b9e6-f4cf527a632a
STRENGT_FORTROLIG: 5ef775f2-61f8-4283-bf3d-8d03f428aa14
EGEN_ANSATT: dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
