TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api
SKJERMEDE_BASE_URL: https://skjermede-personer-pip.intern.nav.no

NORG2_API_V1_URL: https://norg2.prod-fss-pub.nais.io/norg2/api/v1
PROXY_APP_CLIENT_ID: 981be1fb-1379-465f-bddc-7563197aed84

EREG_URL: https://ereg-services.prod-fss-pub.nais.io/ereg/api

VEDTAK_FATTET_TOPIC: klage.vedtak-fattet.v1
DVH_STATISTIKK_TOPIC: klage.kabal-statistikk.v1
BEHANDLING_ENDRET_TOPIC_V2: klage.behandling-endret.v2
BEHANDLING_EVENTS_TOPIC: klage.behandling-events.v1

AIVEN_ES_HOST: elastic-klage-oppgave-es-nav-prod.aivencloud.com
AIVEN_ES_PORT: 26482
AIVEN_ES_SCHEME: https
AIVEN_ES_USE_SSL: true

SAF_BASE_URL: https://saf.prod-fss-pub.nais.io/
SAF_SCOPE: prod-fss.teamdokumenthandtering.saf

KABAL_OPPGAVESTYRING_ALLE_ENHETER: 1c006e8b-c667-4622-9df7-43ed2fd494d6
KABAL_MALTEKSTREDIGERING: 95c25ca2-e3e9-423e-a55f-9bc327c29f96
KABAL_SAKSBEHANDLING: 2b671b60-9650-4839-9139-40999bbb0f71
KABAL_FAGTEKSTREDIGERING: 1edfbdf1-c1bc-4dc6-9cab-4fff1cb7e2a8
KABAL_OPPGAVESTYRING_EGEN_ENHET: e9de217a-7244-45ac-8a06-1994905d7964
FORTROLIG: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
STRENGT_FORTROLIG: ad7b87a6-9180-467c-affc-20a566b0fec0
EGEN_ANSATT: e750ceb5-b70b-4d94-b4fa-9d22467b786b

KABAL_ADMIN: cd78b8e8-73a3-4fb6-8234-7bebb5e5b9e9

CLAM_AV_URL: http://clamav.clamav/scan