ingresses:
  - https://kabal-api.dev.intern.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: klage-fss-proxy.dev-fss-pub.nais.io
  - host: kafka-schema-registry.nais-q.adeo.no
  - host: saf.dev-fss-pub.nais.io
  - host: norg2.dev-fss-pub.nais.io
  - host: ereg-services-q1.dev-fss-pub.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
    ports:
      - name: https
        port: 26482
        protocol: TCP
inboundApplications:
  - application: kabal-frontend
  - application: klage-dittnav-api
  - application: klage-arkiver-journalpost
  - application: k9-klage
    namespace: k9saksbehandling
    cluster: dev-fss
  - application: su-se-bakover
    namespace: supstonad
    cluster: dev-fss
  - application: fpsak
    namespace: teamforeldrepenger
    cluster: dev-fss
  - application: familie-klage
    namespace: teamfamilie
    cluster: dev-gcp
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
kafka_pool: nav-dev
KABAL_OPPGAVESTYRING_ALLE_ENHETER: 7ad08bfe-68d4-4c84-bddd-82d8894fb36e
KABAL_MALTEKSTREDIGERING: 0097d4ff-787d-4180-953a-8d60b7927f32
KABAL_SAKSBEHANDLING: 07add1e7-7195-4c37-828d-fdf23ec6bef1
KABAL_FAGTEKSTREDIGERING: 94d34f17-e325-4ed6-9667-d23041a3f40c
KABAL_OPPGAVESTYRING_EGEN_ENHET: 016fb83f-4e7c-47ec-ae8a-e3efa72a43e7
FORTROLIG: 2980c598-8af7-473f-b7d1-233f785d7001
STRENGT_FORTROLIG: de92036b-c350-471c-9249-753f36acd24d
EGEN_ANSATT: 011af9b0-792d-4d2c-a2eb-9a59fc095002

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"